Repository Dessia-tech/volmdlr, pull requests merged in 2022-12, with the labels that each got.

#565 Fix line3d intersections
  volmdlr/edges.py
Labels: status: ready for review

#568 ArcEllipse3d: new methods
  CHANGELOG.md
  tests/edges/test_arcellipse3d.py
  volmdlr/edges.py
Labels: status: ready for merge

#556 add fix to bool operations
  CHANGELOG.md
  volmdlr/edges.py
  volmdlr/faces.py
Labels: status: ready for merge

#567 add new method linesegment_intersections to FullArc3D
  CHANGELOG.md
  tests/edges/test_fullarc3d.py
  volmdlr/edges.py
Labels: status: ready for merge

#564 Add new method to Line: sort_points_along_line
  CHANGELOG.md
  tests/edges/test_line2d.py
  tests/edges/test_line3d.py
  volmdlr/edges.py
Labels: status: ready for merge

#566 Add new Arcellipse2D methods and unittests for these methods
  CHANGELOG.md
  tests/edges/test_arc_ellipse2d.py
  volmdlr/edges.py
Labels: status: ready for merge

#563 doc: pydocstyle ratchet and weekly decrease
  code_pydocstyle.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/grid.py
  volmdlr/primitives3d.py
  volmdlr/stl.py
  volmdlr/wires.py
Labels: status: ready for merge

#569 New Class wires.Ellipse2d
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  tests/wires/test_ellipse2d.py
  volmdlr/edges.py
  volmdlr/wires.py
Labels: status: ready for merge

#555 feat: serailizing bounding box for shells to avoid recomputation at init
  volmdlr/faces.py
Labels: status: ready for merge, status: ready for review

#576 fix: offset of linesegment was not using unit normal vector
  CHANGELOG.md
  volmdlr/edges.py
Labels: status: ready for merge

#418 Fix LineSegment3D : projection2d
  volmdlr/edges.py
Labels: status: ready for merge

#570 new fix to Line3d intersections
  code_pydocstyle.py
  code_pylint.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/wires.py
Labels: status: ready for merge

#550 Fix: Contour2D/BSplineCurve2D: bounding_rectangle + Unittest (Contour2D.point_belongs)
  CHANGELOG.md
  tests/wires/test_contour2d.py
  tests/wires/test_wire.py
  volmdlr/edges.py
  volmdlr/models/contours.py
  volmdlr/wires.py
Labels: status: ready for merge

#573 Circle3d new methods
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  setup.py
  tests/edges/test_arc3d.py
  tests/wires/test_circle3d.py
  volmdlr/core.py
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/utils/__init__.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: ready for review

#578 fix(barrels): stop importing from dessia_common directly
  CHANGELOG.md
  scripts/faces/BSplineSurface/bspline_surface_definition.py
  scripts/mesh/mesher.py
  tests/faces/test_planeface3d.py
  volmdlr/cloud.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/gmsh_vm.py
  volmdlr/grid.py
  volmdlr/mesh.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/stl.py
Labels: priority: Critical

#583 CylindricalSurface3D new methods
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  tests/faces/test_cylindrical_surface3d.py
  volmdlr/faces.py
Labels: status: ready for review

#585 Refactor line3d intersections
  CHANGELOG.md
  volmdlr/edges.py
  volmdlr/faces.py
Labels: status: ready for review

#582 Add new methods and fix some other from Ellipse3D
  CHANGELOG.md
  tests/wires/test_ellipse3d.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for review

#575 Fix contour2d offset
  CHANGELOG.md
  code_pydocstyle.py
  tests/wires/contour_to_offset.json
  tests/wires/test_contour2d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for review

#579 Add new methods and some fixes to Plane3D
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  tests/faces/test_plane3d.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
Labels: status: ready for merge

#580 Fix: Contour2D.ordering_contour()
  CHANGELOG.md
  code_pylint.py
  tests/wires/contour_not_ordered.json
  tests/wires/contour_ordered.json
  tests/wires/test_contour2d.py
  volmdlr/core_compiled.pyx
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for review

#544 Fix: PlaneFace3D.cut_by_coincident_face
  CHANGELOG.md
  volmdlr/faces.py
Labels: status: ready for merge

#588 Fix bug bonding_box to dict
  volmdlr/core.py
Labels: type: bug

#587 Ci time
  .drone.yml
  .pylintrc
  code_pydocstyle.py
  code_pylint.py
  scripts/ci_scripts.py
  scripts/faces/BSplineSurface/bspline_surface_merge.py
  scripts/faces/union.py
  tests/faces/test_bsplinesurface3d.py
  tests/wires/test_contour2d.py
  volmdlr/code_aster.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/geometry.py
  volmdlr/primitives.py
  volmdlr/primitives2d.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: status: ready for merge

#463 Feat: OpenShell3D.project coincident faces
  CHANGELOG.md
  code_pydocstyle.py
  volmdlr/faces.py
  volmdlr/step.py
Labels: status: changes done

#559 Feat: Generate .vtk file
  CHANGELOG.md
  code_pydocstyle.py
  scripts/mesh/read_msh_file.py
  volmdlr/core.py
  volmdlr/gmsh_vm.py
  volmdlr/grid.py
Labels: status: ready for merge

#592 fix to_dict
  volmdlr/primitives3d.py
Labels: type: bug, status: ready for merge

#594 Refactor BSplineSurface3D.point3d_to_2d()
  CHANGELOG.md
  volmdlr/faces.py
Labels: status: ready for merge

#586 Refactor BSplineSurface3D periodicity to a more efficient and precise method
  CHANGELOG.md
  requirements.txt
  tests/faces/surface3d_8.json
  tests/faces/test_bsplinesurface3d.py
  volmdlr/core.py
  volmdlr/faces.py
  volmdlr/models/bspline_surfaces.py
Labels: status: ready for merge

#596 Change Closedpolygon2d triangulation to a faster method
  CHANGELOG.md
  requirements.txt
  tests/wires/test_closedpolygon2d.py
  volmdlr/wires.py
Labels: status: ready for review

#551 Dev wf step
  scripts/step/shell0.step
  scripts/step/workflow_generic_step_reading.py
  volmdlr/step.py
Labels: status: ready for merge

#599 Refactor: change of basis coordinates
  CHANGELOG.md
  tests/core_compiled/__init__.py
  tests/core_compiled/test_basis2d.py
  tests/core_compiled/test_basis3d.py
  tests/core_compiled/test_frame2d.py
  tests/core_compiled/test_frame3d.py
  volmdlr/core_compiled.pyx
Labels: type: refactor, status: ready for review

#598 To parametric
  scripts/step/read_steps.py
  tests/faces/test_conical_surface3d.py
  tests/faces/test_cylindrical_surface3d.py
  tests/faces/test_toroidal_surface3d.py
  volmdlr/faces.py
  volmdlr/utils/parametric.py
Labels: status: ready for review

#541 Shell triangles
  .pylintrc
  CHANGELOG.md
  code_pylint.py
  volmdlr/core.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/stl.py
Labels: status: ready for review, status: resolve conflicts

#600 Perf: Cylinder.min_distance_to_other_cylinder
  CHANGELOG.md
  scripts/collisions/cylinders_collision.py
  scripts/collisions/test_perf_min_dist.py
  volmdlr/primitives3d.py
Labels: status: ready for merge

#554 Fix: Mesh.delete_duplicated_nodes
  CHANGELOG.md
  volmdlr/faces.py
  volmdlr/gmsh_vm.py
  volmdlr/mesh.py
Labels: status: ready for merge

#603 refactor bsplinecurve discretization_points (performance improvement)
  CHANGELOG.md
  tests/edges/test_bsplinecurve.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/step.py
Labels: status: ready for merge

#604 Bspline curve derivatives
  CHANGELOG.md
  volmdlr/edges.py
Labels: status: ready for merge
