Repository Dessia-tech/volmdlr, pull requests merged in 2022-11, with the labels that each got.

#483 Fix face_intersections || contours_from_edges
  CHANGELOG.md
  volmdlr/faces.py
  volmdlr/wires.py
Labels: ready for merge

#439 Block center
  CHANGELOG.md
  volmdlr/primitives3d.py
Labels: ready for merge

#437 node set triangle3d
  volmdlr/faces.py
Labels: changes requested

#520 Fix: BSplineCurve.abscissa
  CHANGELOG.md
  coverage_script.py
  tests/edges/test_bsplinecurve.py
  volmdlr/edges.py
  volmdlr/models/bspline_curves.py
Labels: ready for review

#500 Unittest: line intersection for face with holes
  CHANGELOG.md
  tests/faces/test_planeface3d.py
Labels: ready for merge

#508 test: adding a frame script
  scripts/ci_scripts.py
  scripts/core/frames.py
Labels: ready for merge

#503 502 Circle2D split by line
  CHANGELOG.md
  tests/wires/__init__.py
  tests/wires/test_circle2d.py
  volmdlr/wires.py
Labels: ready for merge

#480 467 create a class for bounding rectangle
  CHANGELOG.md
  code_pylint.py
  scripts/contours/contour_bounding_rectangle_test.py
  tests/test_bounding_rectangle.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: ready for merge

#524 perf: avoid bbox computation
  volmdlr/core.py
Labels: ready for merge

#506 Fix: sweep step export
  CHANGELOG.md
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: ready for merge

#510 Feat: cylinder interference
  CHANGELOG.md
  scripts/collisions/cylinder_points_belongs.py
  scripts/collisions/cylinders_collision.py
  scripts/collisions/cylinders_interference.py
  scripts/collisions/plot_cylinders_points.py
  tests/primitives3d/__init__.py
  tests/primitives3d/test_cylinder.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
Labels: ready for merge

#515 CylindricalSurface3D.linesegment_intersections
  CHANGELOG.md
  tests/faces/test_cylindrical_face3d.py
  tests/faces/test_cylindrical_surface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
Labels: ready for merge

#284 feat: Take inner contours into account
  CHANGELOG.md
  code_pylint.py
  scripts/contours/cut_by_line.py
  scripts/step/read_steps.py
  scripts/step/strange_gasket.step
  scripts/step/usecase_inner_contour.STEP
  scripts/wires/rolling_circle_in_polygon.py
  volmdlr/__init__.py
  volmdlr/code_aster.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives2d.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: status: ready for merge

#525 New Feature: CylindricalSurface3D.plane_intersection()
  CHANGELOG.md
  tests/edges/test_line2d.py
  tests/edges/test_line3d.py
  tests/faces/test_cylindrical_face3d.py
  tests/faces/test_cylindrical_surface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
Labels: status: ready for merge

#539 Stl binary
  CHANGELOG.md
  scripts/stl/workflow_generic_stl_reading.py
  volmdlr/step.py
  volmdlr/stl.py
Labels: status: ready for merge

#523 Fix: Contour.is_overlapping
  CHANGELOG.md
  tests/wires/test_contour.py
  volmdlr/wires.py
Labels: status: ready for merge

#530 Fix: LineSegment2D.to_wire
  CHANGELOG.md
  tests/edges/test_linesegment2d.py
  volmdlr/edges.py
Labels: status: ready for merge

#536 ci: add upstream updates
  .drone.yml
Labels: status: ready for merge

#542 straight_line_area arcellipse2d
  CHANGELOG.md
  volmdlr/edges.py
Labels: status: ready for review

#552 Fix step export
  scripts/faces/export_to_step.py
  volmdlr/core.py
Labels: status: ready for merge

#518 fix contour2d point belongs when one of the primitives is some kind o…
  code_pylint.py
  scripts/edges/arcs2D.py
  volmdlr/edges.py
  volmdlr/wires.py
Labels: status: ready for merge

#443 Docstrings
  .drone.yml
  code_pydocstyle.py
  scripts/Tutorial/tutorial1.ipynb
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
Labels: status: ready for merge
