Repository Dessia-tech/volmdlr, pull requests merged in 2022-09, with the labels that each got.

#429 test: add to_step on extrusion
  scripts/primitives/extrusion.py
Labels: ready for merge

#435 Wirajan/issue 434 - Create point_distance method for Wire3D
  CHANGELOG.md
  volmdlr/wires.py
Labels: ready for review

#436 Feat: cylinders collision detection
  CHANGELOG.md
  scripts/collisions/cylinders_collision.py
  volmdlr/core_compiled.pyx
  volmdlr/primitives3d.py
Labels: ready for merge

#453 Faster BSplineCurve3D and better info when reading buggy step files
  volmdlr/edges.py
  volmdlr/wires.py
Labels: type: enhancement, type: optimization, ready for merge
