Repository Dessia-tech/volmdlr, pull requests merged in 2022-10, with the labels that each got.

#440 Fix bool operation - substract
  .drone.yml
  coverage_script.py
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: type: bug, ready for merge

#470 fix arc2d translation_inplace bug
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/primitives2d.py
Labels: ready for merge

#461 Fix: Contour3D.average center point
  CHANGELOG.md
  volmdlr/wires.py
Labels: ready for merge

#458 Gmsh Object to read .msh file (& define volmdlr mesh)
  CHANGELOG.md
  code_pylint.py
  coverage_script.py
  volmdlr/gmsh.py
Labels: ready for merge

#473 Testing shared primitives extremities fix
  volmdlr/faces.py
  volmdlr/wires.py
Labels: ready for review

#459 Fix multiple substractions
  .gitignore
  code_pylint.py
  tests/faces/face_to_cut_the_one_with_3holes.json
  tests/faces/face_with_3holes.json
  tests/faces/test_planeface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: ready for review

#479 Feat: Circle.primitives
  CHANGELOG.md
  volmdlr/wires.py
Labels: ready for merge

#468 perf: using bounding rectangle to speedup point belongs of contour2D
  scripts/ci_scripts.py
  scripts/faces/BSplineSurface/bspline_surface_definition.py
  scripts/primitives/cylinders.py
  scripts/shells/operations.py
  volmdlr/wires.py
Labels: ready for merge

#460 Refacor and update old code in mesh.py
  CHANGELOG.md
  code_pylint.py
  scripts/ci_scripts.py
  scripts/mesh/block.msh
  scripts/mesh/model.msh
  scripts/mesh/read_msh_file.py
  volmdlr/core.py
  volmdlr/gmsh_vm.py
  volmdlr/mesh.py
  volmdlr/wires.py
Labels: ready for merge

#487 Add Script & STEP files (Faces3D with inner_contours)
  scripts/ci_scripts.py
  scripts/faces/bsplineface_with_inner_contours.stp
  scripts/faces/faces_with_inner_contours.py
  scripts/faces/planeface_with_inner_contour.step
Labels: ready for review

#490 Fix: Arc2D.split
  CHANGELOG.md
  volmdlr/edges.py
Labels: ready for merge

#496 Fix: LineSegment.abscissa
  CHANGELOG.md
  volmdlr/edges.py
Labels: ready for merge

#493 Fix: Wire.extract primitives
  CHANGELOG.md
  coverage_script.py
  scripts/contours/contour_extract_primtives.py
  tests/wires/test_wire.py
  volmdlr/models/contours.py
  volmdlr/wires.py
Labels: ready for merge, changes done, adding unittests

#498 perf: custom to_dicts to speed up serialization
  .pylintrc
  CHANGELOG.md
  code_pylint.py
  scripts/primitives/extrusion3.py
  volmdlr/cloud.py
  volmdlr/core.py
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/gmsh_vm.py
  volmdlr/grid.py
  volmdlr/models/__init__.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/stl.py
  volmdlr/wires.py
Labels: ready for merge

#499 Feat: PlaneFace3D.cut_by_coincident_face
  CHANGELOG.md
  volmdlr/faces.py
Labels: reviewing, changes done

#497 Fix: Contour2d.cut_by_wire
  CHANGELOG.md
  scripts/contours/contour_cut_by_wire_2.py
  volmdlr/edges.py
  volmdlr/wires.py
Labels: ready for merge
