Repository Dessia-tech/volmdlr, pull requests merged in 2023-06, with the labels that each got.

#869 ExtrusionSurface3D: simplify bsplinecurve3d_to_2d
  CHANGELOG.md
  tests/surfaces/objects_extrusion_tests/extrusionsurface_contour3d_to_2d_contour.json
  tests/surfaces/objects_extrusion_tests/extrusionsurface_contour3d_to_2d_surface.json
  tests/surfaces/test_extrusion_surface3d.py
  volmdlr/edges.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#870 New feature: OpenShell3D.faces_graph
  CHANGELOG.md
  code_pylint.py
  volmdlr/shells.py
Labels: status: ready for merge

#896 BSplineCurve3D: from_step
  .woodpecker.yml
  CHANGELOG.md
  volmdlr/edges.py
Labels: status: ready for merge

#899 Edge from step
  CHANGELOG.md
  volmdlr/edges.py
  volmdlr/step.py
Labels: status: ready for merge

#900 babylondata: removes empty objects
  CHANGELOG.md
  volmdlr/core.py
  volmdlr/templates.py
Labels: status: ready for merge

#901 Feat: OpenShell3D.from_faces
  CHANGELOG.md
  scripts/shells/shells_subtract.py
  volmdlr/shells.py
Labels: status: ready for merge

#904 Refactor: OpenShell3D.faces_graph
  CHANGELOG.md
  volmdlr/shells.py
Labels: status: wait another PR merge

#905 Fix sphere
  CHANGELOG.md
  scripts/primitives/sphere.py
  scripts/primitives/sphere_points.py
  tests/primitives3d/test_sphere.py
  volmdlr/cloud.py
  volmdlr/primitives3d.py
  volmdlr/surfaces.py
Labels: status: ready for review
