Repository Dessia-tech/volmdlr, pull requests merged in 2023-02, with the labels that each got.

#645 Fix opened contour from step
  CHANGELOG.md
  code_pydocstyle.py
  tests/faces/objects_cylindrical_tests/contour_1_0.json
  tests/faces/objects_cylindrical_tests/contour_1_1.json
  tests/faces/objects_cylindrical_tests/surface3d_1.json
  tests/faces/test_bsplinesurface3d.py
  tests/faces/test_conical_surface3d.py
  tests/faces/test_cylindrical_surface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/geometry.py
  volmdlr/gmsh_vm.py
  volmdlr/primitives2d.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: ready for merge

#640 fix BSplineCurve.from_points_interpolation method
  CHANGELOG.md
  code_pydocstyle.py
  volmdlr/edges.py
  volmdlr/faces.py
Labels: status: ready for merge, status: ready for review

#619 step to volmdlr
  .drone.yml
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  coverage.py
  scripts/step/casing.step
  scripts/step/compressor_simplified.step
  scripts/step/read_test1.STEP
  scripts/step/read_test3.STEP
  scripts/step/tormach_wrench.step
  tests/core/__init__.py
  tests/core/test_compositeprimitive.py
  tests/core/test_compositeprimitive2d.py
  tests/core_compiled/test_vector.py
  tests/faces/test_bsplinesurface3d.py
  tests/faces/test_cylindrical_surface3d.py
  tests/faces/test_surface3d.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/utils/intersections.py
  volmdlr/utils/parametric.py
  volmdlr/wires.py
Labels: status: ready for merge

#647 Creates a RevolutionSurface3D class
  CHANGELOG.md
  code_pylint.py
  tests/core_compiled/test_vector2d.py
  tests/core_compiled/test_vector3d.py
  tests/faces/test_revolutionsurface3d.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: status: ready for merge, status: ready for review

#657 Fix: cylinders
  CHANGELOG.md
  scripts/primitives/cylinders.py
  scripts/primitives/cylinders2.py
  volmdlr/primitives3d.py
Labels: status: ready for merge, status: reviewing

#646 Triangle3D performance
  .pyenchant_dessia.dict
  .pylintrc
  CHANGELOG.md
  code_pep8.sh
  code_pydocstyle.py
  code_pylint.py
  setup.py
  tests/wires/test_ellipse2d.py
  volmdlr/cloud.py
  volmdlr/core.py
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/mesh.py
  volmdlr/models/workflows/__init__.py
  volmdlr/primitives.py
  volmdlr/primitives2d.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/stl.py
  volmdlr/templates.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: reviewing, fix_pylint

#660 fix some performance issues for Contour2D. Fix LineSegment.line_inter…
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for merge

#667 Coverage / unittests: core.py
  CHANGELOG.md
  tests/core/test_bounding_box.py
  tests/core/test_bounding_rectangle.py
  tests/core/test_composite_primitive.py
  tests/core/test_composite_primitive2d.py
  tests/core/test_composite_primitive3d.py
  tests/core/test_compositeprimitive2d.py
  tests/core/test_functions.py
  tests/core/test_volume_model.py
  tests/test_bounding_rectangle.py
  volmdlr/core.py
  volmdlr/primitives2d.py
Labels: status: ready for review, status: changes done

#674 Deprecated methods
  CHANGELOG.md
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/geometry.py
  volmdlr/primitives.py
  volmdlr/primitives2d.py
  volmdlr/primitives3d.py
  volmdlr/wires.py
Labels: status: ready for merge, type: refactor

#685 Merge dev_fix_step into dev
  .pyenchant_dessia.dict
  CHANGELOG.md
  volmdlr/cloud.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: type: bug

#572 Feat: Write .msh file
  .drone.yml
  CHANGELOG.md
  code_pylint.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/gmsh_vm.py
  volmdlr/grid.py
  volmdlr/mesh.py
  volmdlr/wires.py
Labels: status: ready for review

#686 Adds angle conversion factor into from_step class methods + new plot methods + some small fixes
  CHANGELOG.md
  code_pylint.py
  tests/step/test_conversion_factor.step
  tests/step/test_step.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: status: ready for merge, status: ready for review

#688 Arc: reverse & ContourMixin: to_polygon (From em_mesh)
  CHANGELOG.md
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives2d.py
  volmdlr/stl.py
  volmdlr/wires.py
Labels: status: reviewing, status: changes done

#693 Improve bspline2D point distance
  CHANGELOG.md
  tests/edges/test_bsplinecurve.py
  volmdlr/edges.py
Labels: status: ready for review

#695 Circle2d: bsplinecurve_intersections
  .pyenchant_dessia.dict
  CHANGELOG.md
  code_pylint.py
  tests/edges/test_bsplinecurve.py
  tests/wires/test_circle2d.py
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for review, status: wait another PR merge

#694 add offset method to BSplineCurve2D
  CHANGELOG.md
  tests/edges/test_bsplinecurve.py
  volmdlr/edges.py
Labels: status: ready for review
