Repository Dessia-tech/volmdlr, pull requests merged in 2023-05, with the labels that each got.

#820 Face3D: from_contours3d
  CHANGELOG.md
  tests/faces/objects_bspline_test/bspline_contour_0_openned_contour.json
  tests/faces/objects_bspline_test/bspline_contour_1_openned_contour.json
  tests/faces/objects_bspline_test/bspline_surface_openned_contour.json
  tests/faces/objects_conical_tests/conical_contour_with_singularity.json
  tests/faces/objects_conical_tests/conical_surface1.json
  tests/faces/objects_conical_tests/conical_surface3d_1.json
  tests/faces/objects_conical_tests/conical_surface3d_2.json
  tests/faces/objects_conical_tests/conical_surface_with_singularity.json
  tests/faces/objects_conical_tests/face_contour1.json
  tests/faces/objects_conical_tests/face_contour2.json
  tests/faces/objects_conical_tests/face_contour3_.json
  tests/faces/objects_conical_tests/face_contour4_.json
  tests/faces/objects_conical_tests/face_from_contours1_0.json
  tests/faces/objects_conical_tests/face_from_contours1_1.json
  tests/faces/objects_cylindrical_tests/contour3d__openned_one_contour_0.json
  tests/faces/objects_cylindrical_tests/contour3d__openned_one_contour_1.json
  tests/faces/objects_cylindrical_tests/contour_1_0.json
  tests/faces/objects_cylindrical_tests/contour_1_1.json
  tests/faces/objects_cylindrical_tests/cylindrical_contour_0_repair_contour2d.json
  tests/faces/objects_cylindrical_tests/cylindrical_contour_1_repair_contour2d.json
  tests/faces/objects_cylindrical_tests/cylindrical_contour_floating_point_error.json
  tests/faces/objects_cylindrical_tests/cylindrical_surface_floating_point_error.json
  tests/faces/objects_cylindrical_tests/cylindrical_surface_repair_contour2d.json
  tests/faces/objects_cylindrical_tests/surface3d_1.json
  tests/faces/objects_cylindrical_tests/surface_openned_one_contour.json
  tests/faces/test_bsplineface3d.py
  tests/faces/test_conicalface3d.py
  tests/faces/test_cylindrical_face3d.py
  tests/surfaces/test_bsplinesurface3d.py
  tests/surfaces/test_conical_surface3d.py
  tests/surfaces/test_cylindrical_surface3d.py
  tests/surfaces/test_periodical_surface.py
  tests/surfaces/test_surface2d.py
  volmdlr/core.py
  volmdlr/faces.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#823 FullArcEllipse3D: split
  CHANGELOG.md
  tests/edges/fullarcellipses_to_split.json
  tests/edges/test_fullarcellipse3d.py
  volmdlr/edges.py
Labels: status: ready for review

#825 Fix: RevoltuionSurface3D.linesegment2d_to_3d
  CHANGELOG.md
  tests/edges/arc3d_split_between_two_points.json
  tests/edges/test_edge.py
  tests/surfaces/objects_revolution_tests/linesegment2d_arc3d.json
  tests/surfaces/objects_revolution_tests/linesegment2d_rotated_primitive.json
  tests/surfaces/objects_revolution_tests/linesegment2d_split_primitive.json
  tests/surfaces/objects_revolution_tests/revolutionsurface_linesegment2d_to_3d.json
  tests/surfaces/test_revolutionsurface3d.py
  volmdlr/edges.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/surfaces.py
Labels: status: ready for review

#824 ArcEllipse3D: translation
  CHANGELOG.md
  tests/edges/test_arcellipse3d.py
  volmdlr/edges.py
Labels: status: ready for review

#802 VolumeModel: to_msh (consider both order 1 and 2)
  CHANGELOG.md
  scripts/mesh/geo_file_1.py
  setup.py
  volmdlr/core.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#828 Vector: is_perpendicular_to
  CHANGELOG.md
  tests/core_compiled/test_vector.py
  volmdlr/core_compiled.pyx
  volmdlr/surfaces.py
Labels: status: ready for review

#815 Fix: OpenShell3D.get_geo_lines (use is_close)
  CHANGELOG.md
  volmdlr/primitives3d.py
  volmdlr/shells.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for review

#826 Fix: ToroidalSurface3D.arc3d_to_2d
  CHANGELOG.md
  tests/surfaces/objects_toroidal_tests/toroidal_surface_bug_2.json
  tests/surfaces/objects_toroidal_tests/toroidal_surface_bug_2_contour_0.json
  tests/surfaces/test_toroidal_surface3d.py
  volmdlr/surfaces.py
Labels: status: ready for review

#835 SphericalSurface: enhance arc3d_to_2d bsplinecurve3d_to_2d
  CHANGELOG.md
  code_pylint.py
  tests/surfaces/objects_spherical_tests/arc_with_two_singularities.json
  tests/surfaces/objects_spherical_tests/contour_any_direction_upper_side.json
  tests/surfaces/objects_spherical_tests/contour_left_side.json
  tests/surfaces/objects_spherical_tests/contour_lower_side.json
  tests/surfaces/objects_spherical_tests/contour_rigth_side.json
  tests/surfaces/objects_spherical_tests/contour_upper_side.json
  tests/surfaces/objects_spherical_tests/spericalsurface1_contour0.json
  tests/surfaces/objects_spherical_tests/spherical_surface_arc3d_to_2d.json
  tests/surfaces/objects_spherical_tests/spherical_surface_arc3d_to_2d_contour3d.json
  tests/surfaces/objects_spherical_tests/sphericalsurface1.json
  tests/surfaces/test_sphericalsurface3d.py
  tests/wires/sphere_with_singularity.step
  tests/wires/test_contour3d.py
  volmdlr/edges.py
  volmdlr/shells.py
  volmdlr/surfaces.py
  volmdlr/utils/parametric.py
  volmdlr/wires.py
Labels: status: ready for review

#840 Fix ExtrusionSurface3D linesegment2d_to_3d
  CHANGELOG.md
  tests/surfaces/objects_extrusion_tests/extrusion_surface_test_linesegment2d_to_3d.json
  tests/surfaces/objects_extrusion_tests/linesegment2d_to_linesegment3d.json
  tests/surfaces/objects_extrusion_tests/linesegment2d_to_self_edge.json
  tests/surfaces/test_extrusion_surface3d.py
  volmdlr/surfaces.py
Labels: status: ready for review

#839 Contour3D: from_step removes repeated primitives in method
  CHANGELOG.md
  tests/wires/contour_with_repeated_edge_in_contour3d.step
  tests/wires/test_contour3d.py
  volmdlr/wires.py
Labels: status: ready for merge

#846 Add optional parameter center to Arc
  CHANGELOG.md
  tests/wires/test_contour2d.py
  volmdlr/edges.py
Labels: status: ready for review

#851 Fix: WireMixin.to_wire_with_linesegments()
  CHANGELOG.md
  volmdlr/cloud.py
  volmdlr/wires.py
Labels: status: ready for merge

#843 Step reader investigation
  CHANGELOG.md
  code_pylint.py
  tests/edges/fullarcellipse3d_point_belongs.json
  tests/edges/fullarcellipse_objects/ellipse2d_point_belongs.json
  tests/edges/test_fullarcellipse2d.py
  tests/edges/test_fullarcellipse3d.py
  tests/faces/objects_toroidal_tests/contour_4_0.json
  tests/faces/objects_toroidal_tests/surface_4.json
  tests/faces/test_toroidalface3d.py
  tests/geometry/clockwise_interior_from_circle3d_circle.json
  tests/geometry/test_geometry.py
  tests/surfaces/objects_toroidal_tests/surface.json
  tests/surfaces/test_toroidal_surface3d.py
  tests/wires/test_contour3d.py
  volmdlr/display.py
  volmdlr/faces.py
  volmdlr/shells.py
  volmdlr/step.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: wait another PR merge

#864 Face3D: Fix face inside
  CHANGELOG.md
  tests/faces/objects_planeface_tests/test_face3_face_inside.json
  tests/faces/objects_planeface_tests/test_face_inside.json
  tests/faces/test_planeface3d.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for merge

#865 fix WireMixin.split_with_sorted_points()
  CHANGELOG.md
  tests/wires/test_contour2d.py
  volmdlr/wires.py
Labels: status: ready for merge
