Repository Dessia-tech/volmdlr, pull requests merged in 2023-12, with the labels that each got.

#1171 Feat: contour3d_to_2d/contour2d_to_3d returns primitives_mapping
  CHANGELOG.md
  tests/surfaces/test_conical_surface3d.py
  tests/surfaces/test_sphericalsurface3d.py
  tests/utils/test_step_reader.py
  volmdlr/faces.py
  volmdlr/surfaces.py
  volmdlr/utils/parametric.py
Labels: status: ready for review

#1146 Improve step parsing
  CHANGELOG.md
  tests/step/test_step.py
  tests/step/test_step_read_lines.stp
  volmdlr/step.py
  volmdlr/utils/step_reader.py
Labels: status: ready for merge, status: ready for review

#1174 Add big refactor
  CHANGELOG.md
  code_pylint.py
  tests/edges/test_bsplinecurve3d.py
  tests/faces/test_cylindricalface3d.py
  tests/faces/test_toroidalface3d.py
  tests/surfaces/test_cylindrical_surface3d.py
  tests/surfaces/test_toroidal_surface3d.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives2d.py
  volmdlr/surfaces.py
  volmdlr/utils/common_operations.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: ready for merge

#1181 ContourMixin: is_ordered()
  CHANGELOG.md
  tests/wires/edge_loop_with_small_edges_and_gaps.json
  tests/wires/test_contour3d.py
  volmdlr/wires.py
Labels: status: ready for review

#1178 Feat: faces primitives_mapping
  CHANGELOG.md
  tests/faces/test_conicalface3d.py
  volmdlr/faces.py
Labels: status: ready for review

#1188 Feat: Face3D.get_face_polygons
  CHANGELOG.md
  tests/faces/test_conicalface3d.py
  volmdlr/faces.py
Labels: status: ready for review

#1200 New feat: ToroidalSurfaces3D.parametric_points_to_3d
  CHANGELOG.md
  tests/surfaces/test_toroidal_surface3d.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1201 SphericalSurfaces3D: parametric_points_to_3d
  CHANGELOG.md
  tests/surfaces/test_sphericalsurface3d.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1203 ExtrusionSurface3D: parametric_points_to_3d
  CHANGELOG.md
  tests/surfaces/test_extrusion_surface3d.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1206 RevolutionSurface3D: parametric_points_to_3d
  CHANGELOG.md
  tests/surfaces/test_revolutionsurface3d.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1207 Plane3D: parametric_points_to_3d
  CHANGELOG.md
  tests/surfaces/test_plane3d.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1209 Refactor DisplayMesh
  CHANGELOG.md
  tests/faces/test_bsplineface3d.py
  tests/faces/test_cylindricalface3d.py
  tests/faces/test_toroidal_face3d.py
  tests/wires/test_closedpolygon2d.py
  volmdlr/cad_simplification.py
  volmdlr/core.py
  volmdlr/discrete_representation.py
  volmdlr/display.py
  volmdlr/faces.py
  volmdlr/shells.py
  volmdlr/stl.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for merge

#1211 BSplineCurve.decompose: decompose the bspline curve into béziers patches of same degree.
  CHANGELOG.md
  tests/edges/bsplinecurve_objects/spiral_bsplinecurve.json
  tests/edges/test_bsplinecurve3d.py
  volmdlr/edges.py
  volmdlr/nurbs/core.pyx
  volmdlr/nurbs/helpers.pyx
  volmdlr/nurbs/operations.py
Labels: status: ready for merge

#1220 Fix step export + LineSegment3D revolution
  CHANGELOG.md
  tests/core_compiled/test_frame3d.py
  volmdlr/core_compiled.pyx
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/shells.py
  volmdlr/wires.py
Labels: status: ready for review

#1223 Add some missing docstrings
  CHANGELOG.md
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for review, fix_pydocstyle

#1213 BSplineSurface3D.decompose: decompose surface into Bézier patches of same degree
  CHANGELOG.md
  tests/surfaces/objects_bspline_test/bsplineface_triangulation_problem_surface.json
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/nurbs/operations.py
  volmdlr/surfaces.py
Labels: status: ready for merge
