Repository Dessia-tech/volmdlr, pull requests merged in 2023-10, with the labels that each got.

#1048 add fixes to circle2d: line_intersections
  .pylintrc
  CHANGELOG.md
  code_pylint.py
  tests/curves/test_circle2d.py
  tests/surfaces/test_plane3d.py
  tests/wires/test_contour2d.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/primitives.py
Labels: status: ready for review, status: changes requested

#1062 add fixes to intersections between a bspline curve and a line_segment
  CHANGELOG.md
  tests/surfaces/objects_extrusion_tests/extrusionsurface_with_small_edge.json
  tests/surfaces/objects_extrusion_tests/extrusionsurface_with_small_edge_contour.json
  tests/surfaces/test_extrusion_surface3d.py
  volmdlr/curves.py
  volmdlr/edges.py
Labels: status: ready for merge

#1060 ArcEllipse3D: is_close + Ellipse3D: discretization_points
  CHANGELOG.md
  tests/curves/test_circle2d.py
  tests/curves/test_circle3d.py
  tests/curves/test_ellipse2d.py
  tests/curves/test_ellipse3d.py
  tests/edges/test_arc3d.py
  tests/edges/test_arcellipse2d.py
  tests/edges/test_arcellipse3d.py
  tests/faces/objects_cylindrical_tests/plane_face_cylindrical_face_intersec.json
  tests/faces/objects_planeface_tests/face_to_cut_the_one_with_3holes.json
  tests/faces/objects_planeface_tests/face_tobe_divided.json
  tests/faces/objects_planeface_tests/face_with_3holes.json
  tests/faces/objects_planeface_tests/plane_face_cylindrical_face_intersec.json
  tests/faces/test_conicalface3d.py
  tests/faces/test_cylindricalface3d.py
  tests/faces/test_planeface3d.py
  volmdlr/curves.py
  volmdlr/faces.py
Labels: status: ready for merge

#1045 CylindricalSurface3D: conicalsurface_intersections
  CHANGELOG.md
  tests/faces/test_planeface3d.py
  tests/surfaces/test_conical_surface3d.py
  tests/surfaces/test_cylindrical_surface3d.py
  tutorials/tutorial_casing.py
  volmdlr/edges.py
  volmdlr/surfaces.py
  volmdlr/utils/common_operations.py
Labels: status: ready for review

#1047 Conical face cylindrical face intersections
  CHANGELOG.md
  code_pylint.py
  tests/edges/test_arcellipse3d.py
  tests/edges/test_bsplinecurve3d.py
  tests/faces/objects_cylindrical_tests/test_cylindrical_faces_split_by_plane_expected_discretization_points.json
  tests/faces/test_cylindricalface3d.py
  tests/faces/test_planeface3d.py
  tests/surfaces/test_cylindrical_surface3d.py
  tests/surfaces/test_plane3d.py
  tests/wires/test_contour2d.py
  volmdlr/core_compiled.pyx
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/surfaces.py
  volmdlr/utils/common_operations.py
  volmdlr/utils/intersections.py
Labels: status: ready for review, status: wait another PR merge

#1065 Fix rectamgular sweep
  CHANGELOG.md
  tests/edges/test_linesegment3d.py
  volmdlr/edges.py
  volmdlr/primitives3d.py
Labels: status: ready for review

#1067 Fix FullArcEllipse3D, FullArcEllipse2D: discretization_points
  CHANGELOG.md
  tests/edges/fullarcellipse_objects/fullarcellipse3d_discretization_points.json
  tests/edges/test_fullarcellipse3d.py
  volmdlr/edges.py
Labels: status: ready for review

#1068 Enhance surfaces parametric operations
  CHANGELOG.md
  code_pylint.py
  tests/faces/test_bsplineface3d.py
  tests/surfaces/objects_bspline_test/BSplineSurface3D_with_Arc3D.json
  tests/surfaces/objects_bspline_test/bsplinesurface_with_fullarcellipse.json
  tests/surfaces/objects_bspline_test/bsplinesurface_with_fullarcellipse_fullarcellipse3d.json
  tests/surfaces/objects_bspline_test/surface3d_8.json
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/surfaces.py
  volmdlr/utils/step_reader.py
Labels: status: ready for review

#1073 Add some missing docstrings
  .woodpecker.yml
  CHANGELOG.md
  code_pydocstyle.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/mesh.py
  volmdlr/primitives3d.py
  volmdlr/shells.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for review

#1077 ClosedPolygon2D: points_in_polygon (Using Parallelism)
  CHANGELOG.md
  volmdlr/core_compiled.pyx
  volmdlr/surfaces.py
  volmdlr/utils/common_operations.py
  volmdlr/wires.py
Labels: status: wait another PR merge

#1084 Fix: MatrixBasedVoxelization boolean operations
  CHANGELOG.md
  tests/discrete_representation/test_matrix_based_voxelization.py
  volmdlr/discrete_representation.py
Labels: type: bug

#1029 Feat: triangles decimation
  CHANGELOG.md
  scripts/ci_scripts.py
  scripts/shells/decimation.py
  setup.py
  volmdlr/shells.py
Labels: type: enhancement, status: ready for merge, type: feature request
