Repository Dessia-tech/volmdlr, pull requests merged in 2023-03, with the labels that each got.

#689 Step reader - handling inconsistencies from step files
  CHANGELOG.md
  volmdlr/cloud.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: status: ready for merge, status: ready for review

#697 Compilation of some functions used in BSplineSurface3D.point2d_to_3d
  CHANGELOG.md
  code_pylint.py
  coverage.py
  setup.py
  volmdlr/bspline_compiled.pyx
  volmdlr/bspline_evaluators.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/mesh.py
  volmdlr/models/casing.py
Labels: status: ready for review

#714 Fix arc split
  CHANGELOG.md
  tests/edges/test_arc2d.py
  tests/edges/test_arc3d.py
  volmdlr/edges.py
Labels: status: ready for review

#715 fix some small fixes for Wire:
  CHANGELOG.md
  volmdlr/wires.py
Labels: status: ready for review

#726 pylint fixes
  .pyenchant_dessia.dict
  .pylintrc
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  volmdlr/cloud.py
  volmdlr/core.py
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/geometry.py
  volmdlr/gmsh_vm.py
  volmdlr/grid.py
  volmdlr/models/bspline_curves.py
  volmdlr/models/bspline_surfaces.py
  volmdlr/models/contours.py
  volmdlr/models/workflows/core.py
  volmdlr/primitives.py
  volmdlr/primitives2d.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/stl.py
  volmdlr/templates.py
  volmdlr/utils/intersections.py
  volmdlr/utils/parametric.py
  volmdlr/wires.py
Labels: status: ready for review

#734 Edge.local_discretization()
  CHANGELOG.md
  tests/edges/test_bsplinecurve.py
  volmdlr/edges.py
Labels: status: ready for merge

#736 fix edge abstract methods
  CHANGELOG.md
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for merge

#721 FullArcEllipse3D and FullArcEllipse2D
  .pylintrc
  CHANGELOG.md
  code_pylint.py
  tests/edges/test_fullarcellipse2d.py
  tests/edges/test_fullarcellipse3d.py
  tests/wires/test_contour2d.py
  volmdlr/cloud.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: status: ready for merge

#727 Surface of linear extrusion + refactor BSplineCurve.abscissa
  .pyenchant_dessia.dict
  .pylintrc
  CHANGELOG.md
  tests/edges/bg_bspline5_.json
  tests/edges/test_bsplinecurve.py
  tests/faces/objects_cylindrical_tests/bsplinecurve3d_bug.json
  tests/faces/objects_cylindrical_tests/cylindrical_surf_bug.json
  tests/faces/objects_extrusion_tests/bspline_extruded_simple.step
  tests/faces/test_cylindrical_surface3d.py
  tests/faces/test_extrusion_surface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/utils/parametric.py
  volmdlr/wires.py
Labels: status: ready for merge

#740 Fix merge contours
  CHANGELOG.md
  code_pylint.py
  tests/edges/test_arc2d.py
  tests/edges/test_bsplinecurve.py
  tests/edges/test_linesegment2d.py
  tests/wires/contour3d_merge_with1.json
  tests/wires/contour3d_merge_with2.json
  tests/wires/expected_contour_merge_with1.json
  tests/wires/expected_contour_merge_with2.json
  tests/wires/test_contour3d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives.py
  volmdlr/primitives2d.py
  volmdlr/primitives3d.py
  volmdlr/utils/common_operations.py
  volmdlr/wires.py
Labels: status: ready for review

#756 Fix arc2d: point_belongs and abscissa.
  CHANGELOG.md
  tests/edges/test_arc2d.py
  volmdlr/edges.py
Labels: status: ready for review

#744 Debug bsplineface - takes into account periodic behavior in parametric domain.
  CHANGELOG.md
  code_pylint.py
  tests/edges/test_bsplinecurve.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for review, status: changes done

#752 Debug face from contours
  .pyenchant_dessia.dict
  CHANGELOG.md
  code_pylint.py
  tests/edges/test_arcellipse2d.py
  tests/edges/test_arcellipse3d.py
  tests/edges/test_bsplinecurve.py
  tests/faces/objects_periodical_surface/bsplinecurve_with_theta_discontinuity.json
  tests/faces/objects_periodical_surface/contour3d__openned_one_contour_0.json
  tests/faces/objects_periodical_surface/contour3d__openned_one_contour_1.json
  tests/faces/objects_periodical_surface/periodicalsurface_with_theta_discontinuity.json
  tests/faces/objects_periodical_surface/surface_openned_one_contour.json
  tests/faces/test_conical_surface3d.py
  tests/faces/test_cylindrical_surface3d.py
  tests/faces/test_periodical_surface.py
  tests/faces/test_surface3d.py
  tests/wires/contour_to_split.json
  tests/wires/test_contour2d.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives.py
  volmdlr/step.py
  volmdlr/utils/parametric.py
  volmdlr/wires.py
Labels: status: ready for merge

#763 Creates introduction topic in volmdlr documentation
  CHANGELOG.md
  doc/source/intro.rst
Labels: status: ready for merge

#748 Fix: BSplineSurface3D.merge_with()
  CHANGELOG.md
  volmdlr/faces.py
Labels: status: ready for merge

#760 Refactor Contour extract_with_points()
  CHANGELOG.md
  scripts/contours/contour_extract_primtives.py
  tests/wires/test_contour2d.py
  tests/wires/test_wire.py
  volmdlr/edges.py
  volmdlr/wires.py
Labels: status: ready for merge
