Repository Dessia-tech/volmdlr, pull requests merged in 2023-11, with the labels that each got.

#1031 Update cad simplification
  CHANGELOG.md
  scripts/cad_simplification/triangle_decimation_simplify.py
  scripts/cad_simplification/triple_extrusion_simplify.py
  scripts/cad_simplification/voxelization_simplify.py
  scripts/cad_simplifier/test_cad_simplification.json
  scripts/cad_simplifier/test_cad_simplifier.py
  scripts/ci_scripts.py
  scripts/step/engine.step
  volmdlr/cad_simplification.py
  volmdlr/shells.py
Labels: type: enhancement, status: ready for review

#1094 SphericalSurface3D: make plot use circle 3d instead of polygon3D.
  .pyenchant_dessia.dict
  CHANGELOG.md
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for merge

#1095 Sphere edge/curves intersections
  .pyenchant_dessia.dict
  CHANGELOG.md
  tests/curves/test_ellipse2d.py
  tests/curves/test_ellipse3d.py
  tests/edges/test_arcellipse2d.py
  tests/edges/test_arcellipse3d.py
  tests/surfaces/test_sphericalsurface3d.py
  volmdlr/surfaces.py
  volmdlr/utils/intersections.py
Labels: status: ready for merge

#1097 Fix: planeface_intersections
  CHANGELOG.md
  volmdlr/faces.py
Labels: status: ready for review

#1085 Fix Frame2D rotation
  CHANGELOG.md
  tests/core_compiled/test_frame2d.py
  tests/core_compiled/test_frame3d.py
  tests/faces/test_bsplineface3d.py
  volmdlr/core_compiled.pyx
  volmdlr/primitives2d.py
  volmdlr/primitives3d.py
Labels: status: ready for merge

#1099 Enhance ExtrusionSurface3D parametric operations + fix ClosedPolygon2D points_in_polygon include_edge_points
  CHANGELOG.md
  tests/faces/objects_extrusion_tests/extrusionface_export_test.json
  tests/faces/objects_extrusion_tests/extrusionface_with_ellipse_test_boundingbox.json
  tests/faces/objects_extrusion_tests/extrusionsurface_inner_contour.json
  tests/faces/objects_extrusion_tests/extrusionsurface_inner_contour_contour_0.json
  tests/faces/objects_extrusion_tests/extrusionsurface_inner_contour_contour_1.json
  tests/faces/test_extrusionface3d.py
  tests/surfaces/objects_extrusion_tests/extrusionsurface_fullarc.json
  tests/surfaces/objects_extrusion_tests/extrusionsurface_fullarc_contour.json
  tests/surfaces/objects_extrusion_tests/extrusionsurface_fullarcellipse.json
  tests/surfaces/objects_extrusion_tests/extrusionsurface_fullarcellipse_contour.json
  tests/surfaces/test_extrusion_surface3d.py
  tests/wires/test_closedpolygon2d.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/faces.py
  volmdlr/surfaces.py
  volmdlr/utils/parametric.py
  volmdlr/wires.py
Labels: status: ready for merge

#1081 Fix: Arc2D is_trigo in rotation / translation / frame_mapping operations
  CHANGELOG.md
  tests/edges/test_arc2d.py
  volmdlr/edges.py
Labels: type: bug, status: ready for merge

#1110 feat: bbox intersection with triangle
  .pylintrc
  CHANGELOG.md
  scripts/core/bbox_triangle_intersection.py
  tests/core/test_bounding_box.py
  volmdlr/core.py
  volmdlr/discrete_representation_compiled.py
Labels: status: ready for review, status: changes done

#1108 Refactor: primitives3d.py Sweep
  CHANGELOG.md
  scripts/primitives/bspline_sweep.py
  scripts/primitives/sweep.py
  tests/edges/test_arc3d.py
  tests/primitives3d/test_sweep.py
  volmdlr/core.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/primitives3d.py
Labels: status: ready for merge

#1114 Perf: babylon_data
  CHANGELOG.md
  volmdlr/core.py
Labels: perf

#1121 Performance: BSplineCurve.line_intersections
  CHANGELOG.md
  tests/faces/test_cylindricalface3d.py
  tests/shells/test_closedshell3d.py
  tests/wires/test_contour2d.py
  volmdlr/__init__.py
  volmdlr/core_compiled.pyx
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/surfaces.py
  volmdlr/utils/intersections.py
Labels: status: ready for merge

#1096 Support to Datakit CrossCadWare STEP file format.
  CHANGELOG.md
  code_pylint.py
  tests/cloud/__init__.py
  tests/utils/__init__.py
  tests/utils/test_step_reader.py
  volmdlr/edges.py
  volmdlr/step.py
  volmdlr/utils/step_reader.py
Labels: status: ready for merge

#1100 Perf: Refactor line segment
  CHANGELOG.md
  code_pylint.py
  tests/faces/test_bsplineface3d.py
  tests/shells/test_closedshell3d.py
  tests/surfaces/objects_bspline_test/bsplinesurface_smallbsplinecurve.json
  tests/surfaces/objects_bspline_test/bsplinesurface_smallbsplinecurve_curve.json
  tests/surfaces/objects_bspline_test/bsplinesurface_with_singularity_linesegment3d_to_2d.json
  tests/surfaces/objects_bspline_test/bsplinesurface_with_singularity_linesegment3d_to_2d_contour.json
  tests/surfaces/objects_conical_tests/conicalsurface_linesegment3d_to_2d.json
  tests/surfaces/objects_conical_tests/conicalsurface_linesegment3d_to_2d_contour.json
  tests/surfaces/test_bsplinesurface3d.py
  tests/surfaces/test_conical_surface3d.py
  tests/surfaces/test_extrusion_surface3d.py
  volmdlr/__init__.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/step.py
  volmdlr/surfaces.py
  volmdlr/utils/parametric.py
  volmdlr/wires.py
Labels: status: ready for review

#1119 Fix matrix based voxelization boolean op
  CHANGELOG.md
  volmdlr/discrete_representation.py
Labels: status: ready for merge

#1127 Feat: Voxelization.from_mesh_data
  CHANGELOG.md
  tests/discrete_representation/stanford_bunny.json
  tests/discrete_representation/test_discrete_representation.py
  tests/discrete_representation/test_matrix_based_voxelization.py
  tests/discrete_representation/test_point_based_voxelization.py
  volmdlr/discrete_representation.py
Labels: status: ready for merge

#1136 Feat: Point2D/3D.in_list
  CHANGELOG.md
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/shells.py
  volmdlr/surfaces.py
  volmdlr/utils/common_operations.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: wait another PR merge

#1090 Feat: OctreeBasedVoxelization
  .pyenchant_dessia.dict
  CHANGELOG.md
  scripts/ci_scripts.py
  scripts/discrete_representation/octree/inner_growing_showcase.py
  scripts/discrete_representation/octree/intersecting_faces_combinations.py
  scripts/discrete_representation/octree/non_homogeneous_showcase.py
  scripts/discrete_representation/voxelization/compare_memory_usage.py
  scripts/discrete_representation/voxelization/interference/compare_boolean_intersection.py
  scripts/discrete_representation/voxelization/interference/compare_boolean_union.py
  scripts/discrete_representation/voxelization/interference/compare_is_intersecting.py
  scripts/discrete_representation/voxelization/interference/interference_surface_showcase.py
  scripts/discrete_representation/voxelization/interference/interference_volume_showcase.py
  scripts/discrete_representation/voxelization/octree/inner_growing_showcase.py
  scripts/discrete_representation/voxelization/octree/intersecting_faces_combinations.py
  scripts/discrete_representation/voxelization/octree/non_homogeneous_showcase.py
  tests/discrete_representation/test_octree_based_voxelization.py
  volmdlr/discrete_representation.py
  volmdlr/discrete_representation_compiled.py
Labels: type: enhancement, status: ready for review

#1133 Refactor: Voxelization classmethods
  CHANGELOG.md
  setup.py
  tests/discrete_representation/test_matrix_based_voxelization.py
  tests/discrete_representation/test_point_based_voxelization.py
  volmdlr/discrete_representation.py
Labels: status: ready for merge, type: refactor

#1106 BoundingBox refactor
  CHANGELOG.md
  code_pylint.py
  scripts/showcases/casing.py
  tests/core/test_assembly.py
  tests/core/test_bounding_box.py
  tests/faces/objects_planeface_tests/test_planeface_intersections.json
  tests/faces/objects_planeface_tests/test_planeface_point_belongs.json
  tests/faces/test_planeface3d.py
  tests/faces/test_toroidalface3d.py
  tests/primitives3d/test_block.py
  volmdlr/core.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
Labels: status: ready for merge, status: changes done

#1128 Enhancement: ToroidalSurface3D/ExtrusionSurface3D parametric operations
  CHANGELOG.md
  tests/surfaces/test_bsplinesurface3d.py
  tests/surfaces/test_cylindrical_surface3d.py
  tests/wires/strange_contour_from_step_file.json
  tests/wires/strange_contour_from_step_primitives.json
  tests/wires/test_contour2d.py
  tests/wires/test_contour3d.py
  volmdlr/core_compiled.pyx
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/surfaces.py
  volmdlr/utils/intersections.py
  volmdlr/utils/step_reader.py
  volmdlr/wires.py
Labels: status: ready for review

#1139 Refactor Boolean Operations: include coincident face intersections
  CHANGELOG.md
  scripts/faces/set_operations_complex_test1.py
  tests/faces/test_planeface3d.py
  tests/shells/shell1(1).json
  tests/shells/shell2(1).json
  tests/shells/test_triangle_shell.py
  volmdlr/faces.py
  volmdlr/shells.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for merge

#1137 Step translator enhancements.
  CHANGELOG.md
  code_pylint.py
  scripts/faces/triangle3d.py
  tests/surfaces/test_toroidal_surface3d.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/nurbs/core.pyx
  volmdlr/step.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for merge

#1144 BSplineCurve.simplify: handles exceptions.
  CHANGELOG.md
  tests/surfaces/objects_cylindrical_tests/cylindricalsurface_small_periodic_bsplinecurve.json
  tests/surfaces/objects_cylindrical_tests/cylindricalsurface_small_periodic_bsplinecurve_contour.json
  tests/surfaces/test_cylindrical_surface3d.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/utils/intersections.py
Labels: status: ready for review

#1152 PeriodicalSurface: handles exceptions in connect_contours method + BSplineCurve: Consider overlaping curves also as periodic.
  CHANGELOG.md
  tests/faces/objects_conical_tests/conicalsurface_openned_contours.json
  tests/faces/objects_conical_tests/conicalsurface_openned_contours_contour_0.json
  tests/faces/objects_conical_tests/conicalsurface_openned_contours_contour_1.json
  tests/faces/test_conicalface3d.py
  volmdlr/edges.py
  volmdlr/surfaces.py
Labels: status: ready for review

#1154 Remove ABC inheritance
  CHANGELOG.md
  volmdlr/cad_simplification.py
  volmdlr/discrete_representation.py
Labels: status: ready for review

#1155 Fix extrusionsurface fullarcellipse3d_to_2d
  CHANGELOG.md
  tests/faces/objects_extrusion_tests/extrusionsurface_fullarcellipse.json
  tests/faces/objects_extrusion_tests/extrusionsurface_fullarcellipse_contour.json
  tests/faces/test_extrusionface3d.py
  tests/surfaces/objects_extrusion_tests/extrusionsurface_fullarcellipse3d_to_2d.json
  tests/surfaces/objects_extrusion_tests/extrusionsurface_fullarcellipse3d_to_2d_fullarcellipse3d.json
  tests/surfaces/test_extrusion_surface3d.py
  volmdlr/curves.py
  volmdlr/faces.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1160 ExtrusionSurface3D: generalization of the _repair_points_order method.
  CHANGELOG.md
  tests/surfaces/objects_extrusion_tests/periodical_extrusionsurface.json
  tests/surfaces/objects_extrusion_tests/periodical_extrusionsurface_bsplinecurve.json
  tests/surfaces/test_extrusion_surface3d.py
  volmdlr/surfaces.py
Labels: status: ready for review

#1161 ToroidalSurface3D: increases precision of point3d_to_2d.
  CHANGELOG.md
  tests/surfaces/objects_toroidal_tests/toroidalsurface_small_arc3d.json
  tests/surfaces/objects_toroidal_tests/toroidalsurface_small_arc3d_contour.json
  tests/surfaces/objects_toroidal_tests/toroidalsurface_small_bsplinecurve.json
  tests/surfaces/objects_toroidal_tests/toroidalsurface_small_bsplinecurve_contour.json
  tests/surfaces/test_toroidal_surface3d.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/step.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for merge
