Repository Dessia-tech/volmdlr, pull requests merged in 2023-04, with the labels that each got.

#754 Test/cylindrical mesh
  CHANGELOG.md
  tests/faces/test_cylindrical_face3d.py
  tests/faces/test_cylindrical_surface3d.py
  tests/faces/test_toroidal_surface3d.py
  volmdlr/assets/logos/volmdlr.jpg
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/geometry.py
Labels: status: ready for merge

#767 Enhance parametric operations
  CHANGELOG.md
  tests/faces/objects_bspline_test/bspline_contour_with_arcs.json
  tests/faces/objects_bspline_test/bspline_surface_with_arcs.json
  tests/faces/objects_conical_tests/conical_contour_with_singularity.json
  tests/faces/objects_conical_tests/conical_surface_with_singularity.json
  tests/faces/test_bsplinesurface3d.py
  tests/faces/test_conical_surface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/utils/parametric.py
Labels: status: ready for merge, status: ready for review

#751 fix closedrounded lines & logo show case
  CHANGELOG.md
  scripts/showcases/logo.py
  tests/wires/test_circle3d.py
  volmdlr/edges.py
  volmdlr/primitives3d.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: ready for merge

#755 Intersections with bspline
  CHANGELOG.md
  scripts/contours/contour_cut_by_wire_2.py
  scripts/primitives/block3d.py
  tests/edges/test_arc2d.py
  tests/edges/test_arcellipse2d.py
  tests/edges/test_edge_intersections.py
  tests/wires/test_circle2d.py
  tests/wires/test_contour2d.py
  tests/wires/test_intersection_contour_with.json
  volmdlr/cloud.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/models/contours.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: resolve conflicts

#741 Plane bisecting two other planes
  CHANGELOG.md
  code_pylint.py
  tests/edges/test_linesegment3d.py
  volmdlr/edges.py
  volmdlr/faces.py
Labels: status: resolve conflicts

#774 refactor cut_by_wire, get_divided_contours and other fixes
  CHANGELOG.md
  tests/wires/test_contour2d.py
  volmdlr/wires.py
Labels: status: ready for merge, status: ready for review

#773 Feat: Contour.is_adjacent
  CHANGELOG.md
  volmdlr/wires.py
Labels: status: ready for review

#761 Fix: Bspline Methods
  CHANGELOG.md
  tests/wires/contour3d_sharing_primitives1.json
  tests/wires/contour3d_sharing_primitives2.json
  tests/wires/test_contour3d.py
  volmdlr/edges.py
Labels: status: ready for review

#770 Fix step reader testing regression
  CHANGELOG.md
  volmdlr/faces.py
Labels: status: ready for review

#769 Debug face from contours3d
  CHANGELOG.md
  tests/faces/objects_cylindrical_tests/cylindrical_contour_bspline_openned_contour.json
  tests/faces/objects_cylindrical_tests/cylindrical_surface_bspline_openned_contour.json
  tests/faces/test_conical_surface3d.py
  tests/faces/test_cylindrical_surface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/utils/parametric.py
  volmdlr/wires.py
Labels: status: ready for merge, status: ready for review

#776 fix bsplinecurve simplify
  CHANGELOG.md
  tests/edges/bsplinecurve_fullarc.json
  tests/edges/test_bsplinecurve.py
  volmdlr/edges.py
Labels: status: ready for merge

#781 Repair contour2d bspline surface
  CHANGELOG.md
  tests/faces/objects_bspline_test/bspline_contour_0_openned_contour.json
  tests/faces/objects_bspline_test/bspline_contour_1_openned_contour.json
  tests/faces/objects_bspline_test/bspline_surface_openned_contour.json
  tests/faces/test_bsplinesurface3d.py
  volmdlr/faces.py
Labels: status: ready for merge

#783 Fix: bug union between 2 block
  CHANGELOG.md
  tests/faces/test_closedshell3d.py
  volmdlr/faces.py
Labels: status: ready for review

#786 FIX: bug with cut by plane
  CHANGELOG.md
  tests/faces/test_closedshell3d.py
  volmdlr/primitives3d.py
Labels: status: ready for review

#745 Coverage: use coverage rc to enable cython coverage
  .coveragerc
  .drone.yml
  CHANGELOG.md
  doc/source/conf.py
  doc/source/index.rst
  scripts/ci_scripts.py
  scripts/primitives/sphere.py
  tests/__init__.py
  volmdlr/bspline_compiled.pyx
  volmdlr/bspline_evaluators.pyx
  volmdlr/bspline_fitting.pyx
  volmdlr/primitives3d.py
  volmdlr/wires.py
Labels: status: ready for merge

#791 Fix: Arc3d minimum_distance to linesegment3D
  CHANGELOG.md
  tests/edges/test_arc3d.py
  volmdlr/edges.py
Labels: status: ready for review

#792 Dessiaobject inheritance up-to-date
  CHANGELOG.md
  volmdlr/edges.py
  volmdlr/gmsh_vm.py
  volmdlr/mesh.py
  volmdlr/primitives3d.py
  volmdlr/wires.py
Labels: status: ready for review

#793 delete Contour2D cut_by_linesegments method
  CHANGELOG.md
  code_pydocstyle.py
  volmdlr/wires.py
Labels: status: ready for review

#794 Extrusion surface linesegment2d to 3d
  CHANGELOG.md
  tests/faces/objects_extrusion_tests/extrusion_surface_isocurve_trimmed.json
  tests/faces/objects_extrusion_tests/extrusion_surface_undefined_direction_linesegment.json
  tests/faces/test_extrusion_surface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
Labels: status: ready for review, status: wait another PR merge

#801 Feat: Edge.is_close
  CHANGELOG.md
  volmdlr/cloud.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/wires.py
Labels: status: ready for merge

#796 fix step reader regressions
  .pyenchant_dessia.dict
  CHANGELOG.md
  tests/edges/test_bsplinecurve.py
  tests/faces/objects_periodical_surface/cylindrical_contour_0_repair_contour2d.json
  tests/faces/objects_periodical_surface/cylindrical_contour_1_repair_contour2d.json
  tests/faces/objects_periodical_surface/cylindrical_surface_repair_contour2d.json
  tests/faces/test_periodical_surface.py
  volmdlr/cloud.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/utils/parametric.py
Labels: status: ready for review

#798 Fix: VolumeModel.get_mesh_lines
  CHANGELOG.md
  volmdlr/core.py
Labels: status: ready for merge

#800 Refactor: ContourMixin.from_points (2D & 3D)
  CHANGELOG.md
  tests/wires/test_contour2d.py
  volmdlr/models/contours.py
  volmdlr/wires.py
Labels: status: ready for merge

#803 Feat: Quadratic Tetrahedron Element
  CHANGELOG.md
  scripts/mesh/mesh_quadratic.msh
  scripts/mesh/read_msh_file.py
  volmdlr/gmsh_vm.py
  volmdlr/mesh.py
Labels: status: ready for merge

#805 GmshParser: to_vtk (quadratic tetrahedron)
  CHANGELOG.md
  volmdlr/gmsh_vm.py
Labels: status: ready for merge

#811 Fix closedshell3D bool intersections
  CHANGELOG.md
  tests/shells/__init__.py
  tests/shells/test_closedshell3d.py
  volmdlr/faces.py
  volmdlr/shells.py
Labels: status: ready for review

#809 new unittests for plane3d
  CHANGELOG.md
  tests/surfaces/test_plane3d.py
  volmdlr/edges.py
  volmdlr/surfaces.py
Labels: status: ready for review

#804 for PR
  CHANGELOG.md
  scripts/faces/surface2d.py
  volmdlr/cloud.py
  volmdlr/edges.py
  volmdlr/primitives2d.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for review

#810 Assembly
  .pyenchant_dessia.dict
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  scripts/primitives/block3d.py
  tests/core/test_assembly.py
  tests/step/test_step.py
  tests/surfaces/objects_bspline_test/arcellipse_on_bsplinesurface.json
  tests/surfaces/objects_bspline_test/bsplinesurface_with_arcellipse.json
  tests/surfaces/objects_extrusion_tests/extrusion_contour_test_arc3d_to_2d.json
  tests/surfaces/objects_extrusion_tests/extrusion_surface_test_arc3d_to_2d.json
  tests/surfaces/test_bsplinesurface3d.py
  tests/surfaces/test_cylindrical_surface3d.py
  tests/surfaces/test_extrusion_surface3d.py
  tests/surfaces/test_revolutionsurface3d.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/shells.py
  volmdlr/step.py
  volmdlr/surfaces.py
Labels: status: ready for review

#814 RevolutionSurface parametric operations
  CHANGELOG.md
  scripts/primitives/block3d.py
  tests/surfaces/objects_revolution_tests/revolution_contour_bug_0.json
  tests/surfaces/objects_revolution_tests/revolution_contour_bug_1.json
  tests/surfaces/objects_revolution_tests/revolution_surface_bug_0.json
  tests/surfaces/objects_revolution_tests/revolution_surface_bug_1.json
  tests/surfaces/objects_revolution_tests/revolutionsurface_simplify_conical.json
  tests/surfaces/objects_revolution_tests/revolutionsurface_simplify_cylindrical.json
  tests/surfaces/objects_revolution_tests/revolutionsurface_simplify_spherical.json
  tests/surfaces/test_extrusion_surface3d.py
  tests/surfaces/test_revolutionsurface3d.py
  volmdlr/faces.py
  volmdlr/geometry.py
  volmdlr/surfaces.py
Labels: status: ready for review
