Repository Dessia-tech/volmdlr, pull requests merged in 2023-01, with the labels that each got.

#606 Fix arc3d_to_2d bsplinesurface and periodicity problem
  CHANGELOG.md
  tests/faces/BSplineSurface3D_with_Arc3D.json
  tests/faces/test_bsplinesurface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
Labels: status: ready for review

#601 change contour3d_to_2d to take into account periodicity
  code_pylint.py
  scripts/step/cone1.step
  scripts/step/cone2.step
  tests/faces/test_conical_surface3d.py
  tests/faces/test_cylindrical_surface3d.py
  tests/faces/test_suface3d.py
  volmdlr/faces.py
  volmdlr/step.py
  volmdlr/utils/parametric.py
Labels: status: ready for merge, status: resolve conflicts

#602 Triangulation
  CHANGELOG.md
  code_pylint.py
  scripts/step/bracket3.step
  tests/faces/test_bsplinesurface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/step.py
  volmdlr/utils/parametric.py
  volmdlr/wires.py
Labels: status: ready for merge, status: ready for review

#610 Fix: BSplineCurve2D.tangent
  CHANGELOG.md
  coverage.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/grid.py
  volmdlr/wires.py
Labels: status: ready for merge

#561 CylindricalFace3D - PlaneFace3D intersections
  CHANGELOG.md
  code_pydocstyle.py
  code_pylint.py
  scripts/contours/contour_merge_with_2.py
  scripts/faces/blocks_set_operations.py
  setup.py
  tests/edges/bsplinecurve2d_1.json
  tests/edges/test_arc_ellipse2d.py
  tests/edges/test_bsplinecurve.py
  tests/edges/test_line2d.py
  tests/edges/test_line3d.py
  tests/edges/test_linesegment2d.py
  tests/edges/test_linesegment3d.py
  tests/faces/plane_face_cylindrical_face_intersec.json
  tests/faces/test_planeface3d.py
  tests/wires/test_contour.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: ready for review, status: wait another PR merge

#614 refactor polygon points belongs
  CHANGELOG.md
  code_pydocstyle.py
  tests/wires/test_closedpolygon2d.py
  volmdlr/core_compiled.pyx
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/wires.py
Labels: status: ready for merge

#611 Fix frame from point vector: error in this methode when the vector is equal to main_axis
  CHANGELOG.md
  volmdlr/core_compiled.pyx
Labels: status: ready for merge

#620 Dev_fix_boundingbox into dev
  CHANGELOG.md
  volmdlr/wires.py
Labels: status: ready for merge

#627 Fix: WireMixin.abscissa
  CHANGELOG.md
  code_pylint.py
  volmdlr/mesh.py
  volmdlr/primitives3d.py
  volmdlr/wires.py
Labels: status: ready for review

#632 Fix OpenRoundedLineSegment2D discretization_points()
  CHANGELOG.md
  scripts/primitives/extrusion2.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives2d.py
  volmdlr/wires.py
Labels: status: ready for merge, status: ready for review

#631 Step unit length conversion factor
  CHANGELOG.md
  code_pydocstyle.py
  volmdlr/core_compiled.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: type: enhancement, status: ready for merge, status: ready for review

#616 Feat/dist points mesh
  CHANGELOG.md
  code_pydocstyle.py
  setup.py
  tests/test_cloud.py
  volmdlr/cloud.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/mesh.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: priority: Medium, status: ready for merge

#634 fix edge display
  CHANGELOG.md
  volmdlr/core.py
  volmdlr/mesh.py
  volmdlr/templates.py
  volmdlr/wires.py
Labels: type: enhancement, priority: Medium, status: ready for merge

#509 Step assemblies: Import
  CHANGELOG.md
  code_pylint.py
  volmdlr/cloud.py
  volmdlr/core.py
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: status: ready for review

#639 fix(from_mesh_data): change point3D call
  CHANGELOG.md
  volmdlr/faces.py
Labels: type: bug, priority: High, status: ready for review

#638 Quick fix bspline curve parametric operations
  CHANGELOG.md
  scripts/step/bracket2.step
  tests/faces/test_bsplinesurface3d.py
  tests/faces/test_conical_surface3d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/models/bspline_surfaces.py
  volmdlr/models/conical_surfaces.py
  volmdlr/primitives3d.py
  volmdlr/step.py
Labels: status: ready for merge, status: ready for review

#636 Fix conical, cylindrical and toroidal surface: face_from_contours
  CHANGELOG.md
  code_pylint.py
  tests/faces/objects_conical_tests/conical_surface1.json
  tests/faces/objects_conical_tests/conical_surface3d_1.json
  tests/faces/objects_conical_tests/conical_surface3d_2.json
  tests/faces/objects_conical_tests/face_contour1.json
  tests/faces/objects_conical_tests/face_contour2.json
  tests/faces/objects_conical_tests/face_contour3_.json
  tests/faces/objects_conical_tests/face_contour4_.json
  tests/faces/objects_conical_tests/face_from_contours1_0.json
  tests/faces/objects_conical_tests/face_from_contours1_1.json
  tests/faces/test_conical_surface3d.py
  volmdlr/faces.py
Labels: status: ready for review

#517 Feat: Create .geo and .msh files (Mesh different geometries with GMSH)
  CHANGELOG.md
  code_pep8.sh
  code_pydocstyle.py
  code_pylint.py
  coverage.py
  requirements.txt
  scripts/ci_scripts.py
  scripts/mesh/geo_file_1.py
  scripts/mesh/geo_file_2.py
  scripts/mesh/geo_file_3.py
  scripts/mesh/read_msh_file.py
  volmdlr/core.py
  volmdlr/core_compiled.pyx
  volmdlr/display.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/gmsh_vm.py
  volmdlr/grid.py
  volmdlr/mesh.py
  volmdlr/primitives3d.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: status: ready for merge
