Repository Dessia-tech/volmdlr, pull requests merged in 2023-08, with the labels that each got.

#973 edges.py: small fixes
  CHANGELOG.md
  volmdlr/edges.py
Labels: status: ready for merge

#970 refactor_bsplinecurve3d_bbox
  CHANGELOG.md
  tests/edges/bsplinecurve_objects/bounding_box_test.json
  tests/edges/test_bsplinecurve3d.py
  volmdlr/edges.py
Labels: status: ready for merge

#972 Small fix Ellipse3d from step
  CHANGELOG.md
  tests/curves/test_ellipse3d.py
  volmdlr/curves.py
Labels: status: ready for merge

#966 BSplineFace3D: fix bounding_box
  CHANGELOG.md
  code_pylint.py
  tests/faces/objects_bspline_test/bsplineface_bbox_test.json
  tests/faces/test_bsplineface3d.py
  volmdlr/faces.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#969 Enhance BSplineCurve intersections
  CHANGELOG.md
  code_pylint.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/gmsh_vm.py
  volmdlr/utils/intersections.py
Labels: status: ready for merge

#974 ExtrusionSurface3D: enhance parametric operations
  CHANGELOG.md
  tests/surfaces/objects_extrusion_tests/contour3d_to_2d_contour.json
  tests/surfaces/objects_extrusion_tests/contour3d_to_2d_contour_2.json
  tests/surfaces/objects_extrusion_tests/contour3d_to_2d_surface.json
  tests/surfaces/objects_extrusion_tests/contour3d_to_2d_surface_2.json
  tests/surfaces/objects_extrusion_tests/point3d_to_2d_surface.json
  tests/surfaces/test_extrusion_surface3d.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#988 Step: small improvements
  CHANGELOG.md
  volmdlr/core.py
  volmdlr/step.py
  volmdlr/utils/step_writer.py
Labels: status: ready for review

#948 [WIP] Fix sewing normals
  CHANGELOG.md
  tests/cloud/test_cloud.py
  tests/wires/test_closedpolygon3d.py
  volmdlr/cloud.py
  volmdlr/core_compiled.pyx
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for merge

#990 Performance: bsplineface bbox
  CHANGELOG.md
  volmdlr/faces.py
Labels: status: ready for merge

#1007 Improve Cylinder / Cone / HollowCylinder usage
  .pyenchant_dessia.dict
  CHANGELOG.md
  scripts/ci_scripts.py
  scripts/primitives/cone.py
  scripts/primitives/cylinder.py
  scripts/primitives/cylinders.py
  scripts/primitives/cylinders2.py
  scripts/primitives/hollow_cylinder.py
  tests/primitives3d/test_cone.py
  tests/primitives3d/test_cylinder.py
  tests/primitives3d/test_hollow_cylinder.py
  volmdlr/primitives3d.py
Labels: type: bug, type: enhancement, status: ready for merge, type: refactor

#1018 Arcellipse3d: new intersections methods
  CHANGELOG.md
  tests/edges/test_arcellipse3d.py
  volmdlr/curves.py
  volmdlr/edges.py
Labels: status: ready for review

#1019 Circle3d: new intersections methods.
  CHANGELOG.md
  code_pylint.py
  tests/curves/test_circle3d.py
  volmdlr/curves.py
Labels: status: ready for review

#1020 Arc3d: New intersections methods.
  CHANGELOG.md
  tests/edges/test_arc3d.py
  tests/edges/test_arcellipse3d.py
  volmdlr/edges.py
Labels: status: ready for review

#1003 add revolution method to BSplineCurve3D
  CHANGELOG.md
  scripts/edges/test_bspline3d_revolution.py
  volmdlr/edges.py
Labels: status: ready for review

#1014 Wire3d/Contour3d - edge intersections
  CHANGELOG.md
  tests/curves/test_ellipse3d.py
  tests/edges/test_arc3d.py
  tests/edges/test_bsplinecurve.py
  tests/edges/test_bsplinecurve3d.py
  tests/edges/test_distances.py
  tests/edges/test_linesegment3d.py
  tests/wires/test_contour3d.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/models/contours.py
  volmdlr/primitives3d.py
  volmdlr/stl.py
  volmdlr/surfaces.py
  volmdlr/utils/common_operations.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: ready for review

#1002 new feature: Face3D.point_distance()
  CHANGELOG.md
  tests/faces/test_face3d.py
  volmdlr/faces.py
  volmdlr/wires.py
Labels: status: ready for merge

#1004 remove normalize methods
  CHANGELOG.md
  scripts/Tutorial/ellipse.py
  scripts/Tutorial/planeFace.py
  scripts/Tutorial/tore.py
  scripts/contours/contour_split.py
  scripts/distance/cyl_cyl.py
  scripts/distance/cyl_pf.py
  scripts/distance/tore_cyl.py
  scripts/distance/tore_pf.py
  scripts/distance/tore_tore.py
  scripts/faces/planar.py
  scripts/showcases/random_casing.py
  scripts/wires/roundedlines.py
  tests/core_compiled/test_vector2d.py
  tests/core_compiled/test_vector3d.py
  tests/test_core.py
  volmdlr/core_compiled.pyx
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/geometry.py
  volmdlr/mesh.py
  volmdlr/primitives2d.py
  volmdlr/primitives3d.py
  volmdlr/stl.py
  volmdlr/surfaces.py
  volmdlr/utils/common_operations.py
  volmdlr/wires.py
Labels: status: ready for review

#1013 Step import: handles when there is an empty assembly in the file.
  CHANGELOG.md
  volmdlr/step.py
Labels: status: ready for review

#903 Feat: Voxelization
  .pyenchant_dessia.dict
  CHANGELOG.md
  coverage.py
  scripts/ci_scripts.py
  scripts/discrete_representation/pixelization/pixelization_boolean_operations.py
  scripts/discrete_representation/pixelization/pixelization_filling.py
  scripts/discrete_representation/pixelization/pixelization_from_closed_polygon.py
  scripts/discrete_representation/pixelization/pixelization_inverse.py
  scripts/discrete_representation/voxelization/interference_surface_showcase.py
  scripts/discrete_representation/voxelization/interference_volume_showcase.py
  scripts/discrete_representation/voxelization/step_file_voxelization.py
  scripts/discrete_representation/voxelization/stl_file_voxelization.py
  scripts/discrete_representation/voxelization/volume_model_matrix_based_voxelization.py
  scripts/discrete_representation/voxelization/volume_model_point_based_voxelization.py
  scripts/discrete_representation/voxelization/voxelization_filling.py
  scripts/discrete_representation/voxelization/voxelization_inverse.py
  scripts/discrete_representation/voxelization/voxelization_moving.py
  setup.py
  tests/discrete_representation/__init__.py
  tests/discrete_representation/test_discrete_representation.py
  tests/discrete_representation/test_matrix_based_voxelization.py
  tests/discrete_representation/test_pixelization.py
  tests/discrete_representation/test_point_based_voxelization.py
  volmdlr/curves.py
  volmdlr/discrete_representation.py
  volmdlr/discrete_representation_compiled.py
  volmdlr/edges.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#997 BSplineSurface3D: partial removal of dependencies on geomdl objects.
  CHANGELOG.md
  code_pylint.py
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/edges.py
  volmdlr/nurbs/core.pyx
  volmdlr/nurbs/fitting.py
  volmdlr/nurbs/helpers.pxd
  volmdlr/nurbs/helpers.pyx
  volmdlr/nurbs/operations.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for merge

#1010 BSplineSurface3D: point3d_to_2d optimization
  CHANGELOG.md
  code_pylint.py
  tests/edges/arc_objects/arc2d_point_belongs.json
  tests/edges/test_arc2d.py
  tests/edges/test_edge_intersections.py
  tests/faces/test_bsplineface3d.py
  tests/faces/test_revolutionface3d.py
  tests/surfaces/objects_bspline_test/contour3d_to_2d_small_primitives_contour.json
  tests/surfaces/objects_bspline_test/contour3d_to_2d_small_primitives_surface.json
  tests/surfaces/objects_bspline_test/surface_with_singularity.json
  tests/surfaces/objects_bspline_test/surface_with_singularity_contour.json
  tests/surfaces/objects_revolution_tests/arc3d_to_2d_arc3d.json
  tests/surfaces/objects_revolution_tests/arc3d_to_2d_arc3d_2.json
  tests/surfaces/objects_revolution_tests/arc3d_to_2d_surface.json
  tests/surfaces/objects_revolution_tests/arc3d_to_2d_surface_2.json
  tests/surfaces/test_bsplinesurface3d.py
  tests/surfaces/test_revolutionsurface3d.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/step.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for review, status: wait another PR merge

#1017 BSplineSurface3D fitting
  .pyenchant_dessia.dict
  CHANGELOG.md
  code_pylint.py
  setup.py
  tests/curves/test_ellipse3d.py
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/__init__.py
  volmdlr/bspline_fitting.pyx
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/nurbs/fitting.py
  volmdlr/nurbs/operations.py
  volmdlr/shells.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for review

#1021 BSplineSurface3D: split
  CHANGELOG.md
  code_pylint.py
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/nurbs/operations.py
  volmdlr/surfaces.py
Labels: status: wait another PR merge
