Repository Dessia-tech/volmdlr, pull requests merged in 2024-02, with the labels that each got.

#1261 BSplineSurface3D: point_inversion_grid_search
  CHANGELOG.md
  tests/faces/objects_bspline_test/bsplineface_grid_search_contour.json
  tests/faces/objects_bspline_test/bsplineface_grid_search_surface.json
  tests/faces/test_bsplineface3d.py
  volmdlr/core.py
  volmdlr/faces.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for merge

#1269 ConicalSurface3D: Refactors definition in accordance with ISO 10303 to better precision.
  CHANGELOG.md
  tests/edges/test_linesegment3d.py
  tests/surfaces/test_conical_surface3d.py
  volmdlr/core.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1270 ArcEllipse3D/FullArcEllipse3D: to_step
  CHANGELOG.md
  tests/edges/test_edge.py
  volmdlr/curves.py
  volmdlr/edges.py
Labels: status: ready for review

#1285 Optimize CI
  .drone.yml
  CHANGELOG.md
  code_pylint.py
  scripts/ci_scripts.py
  tests/display/test_display.py
  tests/shells/test_shell3d.py
  tests/shells/test_triangle_shell.py
  tests/surfaces/test_periodical_surface.py
Labels: priority: High, status: ready for review

#1282 PREREQUISITE TO #1271 Reference Path : FullArc2D can be generated from 3 points
  CHANGELOG.md
  volmdlr/edges.py
Labels: priority: High

#1273 Refactor: optimize mesh usage
  CHANGELOG.md
  scripts/cad_simplification/alpha_wrap_simplify.py
  scripts/cad_simplification/triangle_decimation_simplify.py
  scripts/cad_simplification/triple_extrusion_simplify.py
  scripts/cad_simplification/voxelization_simplify.py
  scripts/discrete_representation/voxelization/step_file_voxelization.py
  scripts/discrete_representation/voxelization/stl_file_voxelization.py
  scripts/discrete_representation/voxelization/volume_model_matrix_based_voxelization.py
  scripts/discrete_representation/voxelization/volume_model_point_based_voxelization.py
  scripts/discrete_representation/voxelization/voxelization_decimation.py
  scripts/discrete_representation/voxelization/voxelization_filling.py
  scripts/discrete_representation/voxelization/voxelization_inverse.py
  scripts/discrete_representation/voxelization/voxelization_moving.py
  scripts/display/mesh3d.py
  scripts/step/read_test1.STEP
  scripts/step/read_test3.STEP
  scripts/step/usecase_inner_contour.STEP
  tests/core/test_volume_model.py
  tests/display/test_mesh3d.py
  volmdlr/cad_simplification.py
  volmdlr/core.py
  volmdlr/discrete_representation.py
  volmdlr/discrete_representation_compiled.py
  volmdlr/display.py
Labels: status: ready for review, status: changes requested

#1274 Fix step export with wireframe models
  CHANGELOG.md
  scripts/step/read_test1.STEP
  scripts/step/read_test3.STEP
  scripts/step/usecase_inner_contour.STEP
  tests/core/compound_export.stp
  tests/core/compound_geometric_set.step
  tests/core/test_compound.py
  tests/step/test_step.py
  tests/step/test_step_read_lines.stp
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/step.py
  volmdlr/utils/step_reader.py
  volmdlr/wires.py
Labels: status: ready for review

#1286 BSplineSurface3D: improves point_inversion_grid_search convergence.
  CHANGELOG.md
  tests/surfaces/objects_bspline_test/bsplinesurface_point3d_to_2d_grid_search_1.json
  tests/surfaces/objects_bspline_test/bsplinesurface_point3d_to_2d_grid_search_2.json
  tests/surfaces/objects_bspline_test/bsplinesurface_point3d_to_2d_grid_search_3.json
  tests/surfaces/objects_bspline_test/bsplinesurface_point3d_to_2d_grid_search_4.json
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1291 Fix _fix_start_end_singularity_point_at_parametric_domain from BSplineSurface3D
  CHANGELOG.md
  tests/faces/test_bsplineface3d.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1279 Fix duplicates in step translation
  CHANGELOG.md
  tests/step/cone.step
  tests/step/test_step.py
  volmdlr/step.py
  volmdlr/wires.py
Labels: status: ready for merge

#1276 Fix: Contour2D.merge_with (use abs_tol)
  CHANGELOG.md
  volmdlr/wires.py
Labels: status: ready for merge

#1277 BSplineSurface3D: Iso curves
  CHANGELOG.md
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/edges.py
  volmdlr/mesh.py
  volmdlr/nurbs/operations.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1289 BezierCurve split
  CHANGELOG.md
  tests/edges/test_beziercurve3d.py
  volmdlr/nurbs/operations.py
Labels: status: ready for merge

#1295 FullArc3D: new method fullarc_intersections
  CHANGELOG.md
  tests/edges/test_fullarc3d.py
  volmdlr/edges.py
Labels: status: ready for merge

#1309 Fix some wires constructors: connected edges must share vertices. (part 1)
  CHANGELOG.md
  code_pylint.py
  tests/primitives3d/test_sweep.py
  tests/wires/expected_contour_merge_with1.json
  tests/wires/expected_contour_merge_with2.json
  tests/wires/test_contour2d.py
  volmdlr/curves.py
  volmdlr/edges.py
  volmdlr/utils/common_operations.py
  volmdlr/wires.py
Labels: status: ready for review
