Repository Dessia-tech/volmdlr, pull requests merged in 2024-01, with the labels that each got.

#1231 BSplineSurface3D: extract_curves
  CHANGELOG.md
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/nurbs/operations.py
  volmdlr/surfaces.py
Labels: status: ready for review

#1238 Face3D: enhance from_contours3d
  CHANGELOG.md
  tests/faces/objects_toroidal_tests/face_with_inner_contour_contour0.json
  tests/faces/objects_toroidal_tests/face_with_inner_contour_contour1.json
  tests/faces/objects_toroidal_tests/face_with_inner_contour_surface.json
  tests/faces/objects_toroidal_tests/repair_inner_contour_periodicity_contour_0.json
  tests/faces/objects_toroidal_tests/repair_inner_contour_periodicity_contour_1.json
  tests/faces/objects_toroidal_tests/repair_inner_contour_periodicity_surface.json
  tests/faces/test_toroidal_face3d.py
  tests/faces/test_toroidalface3d.py
  volmdlr/faces.py
  volmdlr/surfaces.py
Labels: status: ready for review

#1237 Fix bspline abscissa
  CHANGELOG.md
  tests/edges/bsplinecurve_objects/test_bspline_local_discretizations.json
  tests/edges/test_arcellipse3d.py
  tests/edges/test_bsplinecurve2d.py
  tests/edges/test_bsplinecurve3d.py
  tests/faces/test_toroidalface3d.py
  tests/surfaces/test_conical_surface3d.py
  tests/surfaces/test_cylindrical_surface3d.py
  tests/surfaces/test_toroidal_surface3d.py
  tests/wires/test_contour2d.py
  volmdlr/core.py
  volmdlr/edges.py
  volmdlr/nurbs/operations.py
  volmdlr/surfaces.py
  volmdlr/utils/intersections.py
  volmdlr/wires.py
Labels: status: ready for review

#1239 Add _serializable_dict to points and vectors objects
  CHANGELOG.md
  volmdlr/core_compiled.pyx
Labels: status: ready for review

#1242 Feat: Exact BSplineCurve merge_with
  CHANGELOG.md
  tests/edges/test_bsplinecurve2d.py
  volmdlr/edges.py
  volmdlr/nurbs/operations.py
Labels: status: ready for merge

#1241 BSplineSurface3D: point3d_to_2d
  CHANGELOG.md
  setup.py
  tests/faces/objects_bspline_test/bsplineface_periodical_spiral_contour.json
  tests/faces/objects_bspline_test/bsplineface_periodical_spiral_surface.json
  tests/faces/test_bsplineface3d.py
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/nurbs/operations.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1212 Re-refactor mesh
  CHANGELOG.md
  coverage.py
  scripts/ci_scripts.py
  scripts/display/mesh3d.py
  scripts/display/mesh_decimation.py
  tests/core/test_volume_model.py
  tests/display/__init__.py
  tests/display/models/simple.stl
  tests/display/test_display.py
  tests/display/test_mesh3d.py
  tests/shells/test_closedshell3d.py
  tests/shells/test_shell3d.py
  tests/shells/test_shells_distance2.json
  volmdlr/core.py
  volmdlr/discrete_representation.py
  volmdlr/display.py
  volmdlr/faces.py
  volmdlr/nurbs/fitting.py
  volmdlr/shells.py
  volmdlr/stl.py
  volmdlr/surfaces.py
  volmdlr/wires.py
Labels: status: ready for merge

#1240 Remove surfaces duplicated attributes
  CHANGELOG.md
  volmdlr/surfaces.py
Labels: status: ready for merge

#1194 Refactor faces triangulation
  CHANGELOG.md
  tests/discrete_representation/test_matrix_based_voxelization.py
  tests/discrete_representation/test_octree_based_voxelization.py
  tests/discrete_representation/test_point_based_voxelization.py
  tests/faces/test_bsplineface3d.py
  tests/faces/test_face3d.py
  tests/faces/test_sphericalface3d.py
  tests/faces/test_toroidalface3d.py
  tests/shells/test_closedshell3d.py
  volmdlr/edges.py
  volmdlr/faces.py
  volmdlr/step.py
  volmdlr/surfaces.py
  volmdlr/templates.py
  volmdlr/wires.py
Labels: status: reviewing, status: changes requested

#1249 Fix testing
  CHANGELOG.md
  tests/faces/objects_bspline_test/bsplineface_closed_surface_2.json
  tests/faces/objects_bspline_test/bsplineface_closed_surface_2_contour.json
  tests/faces/objects_bspline_test/bsplineface_closed_surface_3.json
  tests/faces/objects_bspline_test/bsplineface_closed_surface_contour_3.json
  tests/faces/objects_bspline_test/bsplineface_closed_surface_contour_not_at_bounds_contour.json
  tests/faces/objects_bspline_test/bsplineface_closed_surface_contour_not_at_bounds_surface.json
  tests/faces/objects_bspline_test/bsplineface_spiral_bug_contour.json
  tests/faces/objects_bspline_test/bsplineface_spiral_bug_surface.json
  tests/faces/objects_bspline_test/small_bsplineface_closed_surface_contour.json
  tests/faces/objects_bspline_test/small_bsplineface_closed_surface_surface.json
  tests/faces/test_bsplineface3d.py
  tests/surfaces/objects_bspline_test/bsplinecurve3d_to_2d_vclosed_surface_test.json
  tests/surfaces/objects_bspline_test/bsplinecurve3d_to_2d_vclosed_surface_test_curve.json
  tests/surfaces/test_bsplinesurface3d.py
  volmdlr/surfaces.py
Labels: status: ready for merge

#1257 BSplineCurve: trim on periodic curves.
  CHANGELOG.md
  tests/edges/test_bsplinecurve3d.py
  volmdlr/edges.py
  volmdlr/surfaces.py
Labels: status: ready for merge
